### PR TITLE
refactor: create helper function structuredClone and use *old* way

### PR DESCRIPTION
**Pull request by danielpeintner**
point all functions to it so that in future we can easily update

fixes https://github.com/eclipse-thingweb/node-wot/issues/1252

### CODE REVIEW

**Comment by danielpeintner** [comment]
Note: in package `td-tools` we use `JSON.parse(JSON.stringify())` also but I don't think the helper functions belongs to `td-tools` package.

https://github.com/eclipse-thingweb/node-wot/blob/1d2e67e04dc7805547aa901ab2b2c550f256e1e7/packages/td-tools/src/td-parser.ts#L222

Hence we can just use it in packages that depend on `core`.

**Comment by relu91** [comment]
I'm not sure that we should add this if we are not 100% sure that this is a bug of the current supported Nodejs versions. From the issue is not clear if the submitter is just using and old version or not.

**Comment by danielpeintner** [comment]
I just feel it is not worth to keep the built-in `structuredClone` if it causes issues. After it was first introduced in https://github.com/eclipse-thingweb/node-wot/pull/1105 we had to partly revert it in https://github.com/eclipse-thingweb/node-wot/pull/1152 because of issues. Now we see new issues popping up.

Hence I think it is an improvement until it is better supported. Moreover, with this change we can easily update the code once we feel comfortable.
Anyhow, if others think we should not make the change it is fine by me also.

**Review by relu91 — APPROVED** [review]
As pointed into the commiter call I'm ok merging this PR, it's just refectoring the code to have a single point where to update. We can refactor later if needed.

**Pull request merged**
