### PR TITLE
feat: support special AID treatment for ranges

### PR DESCRIPTION
**Pull request by danielpeintner**
fixes https://github.com/eclipse-thingweb/node-wot/issues/1128

### CODE REVIEW

**Review by relu91 — APPROVED** [review]
LGTM.

**Comment by relu91** [comment]
It seems we have dangling and random failing macos tests for node 18 😢 . But they are not related to this PR.

**Comment by JKRhb** [comment]
> It seems we have dangling and random failing macos tests for node 18 😢 . But they are not related to this PR.

Yeah, I now restarted the workflow a second time, if it keeps failing then maybe we need to exclude this combination from the CI :/

**Comment by JKRhb** [comment]
Okay, now it worked 🤔 OPC UA seems to be a bit unreliable here :/

**Comment by relu91** [comment]
>Okay, now it worked 🤔 OPC UA seems to be a bit unreliable here :/

Yeah, we have to dig deeper, it might be some un-closed resources.

**Pull request merged**
