### PR TITLE
feat(coap-server): add support for URI variables

### LINKED ISSUE #1015: URI Variables in CoAP are not supported
[Smart coffee machine Thing](http://plugfest.thingweb.io:8083/smart-coffee-machine) produces CoAP forms even if there are uri variables for that affordance. But there is no support for that in CoAP so those forms are not usable at all. Either the support for URI variables should be implemented or forms should not be generated for coap in that case.

### PR DESCRIPTION
**Pull request by JKRhb**
Resolves #1015.

### CODE REVIEW

**Review by egekorkan — APPROVED** [review]

**Comment by JKRhb** [comment]
Thank you for your approval, @egekorkan :) In the last two commits, I applied some additional refactoring/simplification, the functionality itself should remain unchanged, though.

**Review by danielpeintner — APPROVED** [review]
LGTM

**Comment by JKRhb** [comment]
> LGTM

Thank you! Is it okay for you to squash the fixup commits and then merge the PR? Or would you prefer the squash + merge approach?

**Comment by danielpeintner** [comment]
I would "squash and merge" once we merge the PR.
I like this way best since it keeps the history of the PR till to the end and the final commit is clean when it gets merged into the master...

**Pull request merged**
