### PR TITLE
chore(ci): re-enable Node 20

### LINKED ISSUE #1004: Node.js 20 workflow causes issues with modbus and mbus binding (related to serialport)
We need to investigate the reason why Node.js 20 is not working as expected

----
A proposal could be to run Node.js 16 and 18 only (for now) and we investigate why mbus and modbus are failing with Node.js 20.
What do you think?

_Originally posted by @danielpeintner in https://github.com/eclipse-thingweb/node-wot/issues/995#issuecomment-1553062342_

### PR DESCRIPTION
**Pull request by JKRhb**
This PR updates the node-mbus dependency, incorporating a fix for Node 20, and re-enables the corresponding CI workflow.

Fixes #1004.

### CODE REVIEW

**Comment by JKRhb** [comment]
Hmm. For some reason, the CI still fails on Node 20 (but for a different reason now?) I will investigate this a bit more.

**Comment by JKRhb** [comment]
I have been able to identify the installation step of npm 7 as the last remaining cause of this issue :) A full fix should therefore be around the corner.

**Comment by JKRhb** [comment]
The PR should now be ready for review :)

**Review by relu91 — APPROVED** [review]
Perfect! thank you @JKRhb 🎉. I'm also glad that we finally can get off that custom step for installing npm 7.  Good to go.

**Review by danielpeintner — CHANGES_REQUESTED** [review]
Very good, thank you 👍

Can you remove also the following line in this PR
https://github.com/eclipse-thingweb/node-wot/blob/597f34dc6e32a3b7a68117d3ac51830c42a6df81/README.md?plain=1#L103

**Review by danielpeintner — APPROVED** [review]

**Pull request merged**
