### PR TITLE
Remove AID tooling

### PR DESCRIPTION
**Pull request by danielpeintner**
TODOs before merging
* [x] Merge https://github.com/eclipse-thingweb/td-tools/pull/7
* [X] ~~Push new package on NPM~~ aas-aid package available on NPM (see https://www.npmjs.com/package/@thingweb/aas-aid)
* [x] ~~Clean-up dependencies ?~~ Looked into dependencies. Nothing to remove so far.

fixes https://github.com/eclipse-thingweb/node-wot/issues/1249

### CODE REVIEW

**Review by relu91 — APPROVED** [review]
Agree with the timeline, let's merge this when all the boxes are ticked.

**Comment by danielpeintner** [comment]
I believe the PR is now ready to be merged. All TODOs are done and a *new* aas-aid package has been pushed on NPM (see https://www.npmjs.com/package/@thingweb/aas-aid)

**Comment by relu91** [comment]
Good! we can merge from my side as well.

**Review by egekorkan — APPROVED** [review]
Reviewed the changed files as well and it looks good to me

**Pull request merged**
