### PR TITLE
fix: properly identify readall and writeall op's

### PR DESCRIPTION
**Pull request by danielpeintner**
fixes https://github.com/eclipse/thingweb.node-wot/issues/949

~~https://github.com/eclipse/thingweb.node-wot/issues/965~~

### CODE REVIEW

**Comment by relu91** [comment]
Is the issue linked the right one?

**Comment by danielpeintner** [comment]
> Can't we simplify the code to:
> 
> ```ts
> allReadOnly = !!thing.properties[propertyName].readOnly
> allWriteOnly = !!thing.properties[propertyName].writeOnly
> ```

I added some basic tests and apparently it does not work.
To be honest I don't exactly understand why ... feel free to try it yourself.

**Comment by relu91** [comment]
@danielpeintner all tests are green, which one is failing?

**Comment by danielpeintner** [comment]
> @danielpeintner all tests are green, which one is failing?

The test fails if I apply the changes you proposed.

```
allReadOnly = !!thing.properties[propertyName].readOnly
allWriteOnly = !!thing.properties[propertyName].writeOnly
```

**Comment by relu91** [comment]
Yes sorry, the correct form should be the following:
```ts
allReadOnly = allReadOnly || !!thing.properties[propertyName].readOnly
allWriteOnly = allWriteOnly || !!thing.properties[propertyName].writeOnly
```

**Comment by danielpeintner** [comment]
@relu91 do you feel strongly about your proposed change since I personally feel the current version might be more verbose but also clearer (at least to me 🤷‍♂️).

Anyhow, If you think we should change it I can do it 👍

**Comment by relu91** [comment]
yes, you are right the proposed changes are too "ninja coding" style. Let's merge this PR as it is.

**Pull request merged**
