### PR TITLE
fix: add missing packages for serdes.ts

### PR DESCRIPTION
**Pull request by danielpeintner**
Note: I used the exact same version for `is-absolute-url` and `url-toolkit` as in https://github.com/eclipse-thingweb/node-wot/blob/f63b72951fa9190ced8126e2f6b4cfe045b148bf/packages/td-tools/package.json#L20-L22 to avoid issues.

fixes https://github.com/eclipse-thingweb/node-wot/issues/1317

### CODE REVIEW

**Comment by danielpeintner** [comment]
I also wonder if this justifies a quick new release, because the library is not really usable without the fix, right ...

@hasanheroglu ?

**Review by JKRhb — APPROVED** [review]

**Comment by JKRhb** [comment]
> I also wonder if this justifies a quick new release, because the library is not really usable without the fix, right ...

I think that would make sense :)

**Comment by hasanheroglu** [comment]
> I also wonder if this justifies a quick new release, because the library is not really usable without the fix, right ...
> 
> @hasanheroglu ?

As a workaround, one can install the missing dependencies separately, but yes the library is broken.

**Comment by danielpeintner** [comment]
@relu91 are you fine with releasing an update ASAP ?

**Review by relu91 — APPROVED** [review]
Definitely ok for releasing

**Pull request merged**
