### PR TITLE
ci: reintroduce macOS and Windows testing on the `master` branch

### PR DESCRIPTION
**Pull request by JKRhb**
As discussed in #882, this PR reintroduces automated testing with Windows and macOS on the `master` branch. To limit the use of macOS and Windows to the `master` branch, I adjusted the testing matrix so that the two OSs are excluded if the current branch should not be `master`. This rendered the other workflow definition file obsolete, which is why I removed it.

While I was at it, I slightly adjusted the `on` section in the workflow file so that the workflow only runs in the `push` case when it is a push to the `master` branch. This resolves the slight annoyance that the CI ran twice for some reason in the case of a PR coming from a fork.

With this PR, we could consider #882 resolved. However, we could also leave it open and evaluate if macOS and Windows testing should be reintroduced for PRs as well.

### CODE REVIEW

**Review by danielpeintner — COMMENTED** [review]
LGTM

The only use-case I have in mind is the following. At the moment MacOS and Windows are run only against master. Good so far, However, how can we (even manually) trigger the CI to run against all OS'es ... because we want to check that also in some special cases...

**Comment by JKRhb** [comment]
I think with the `workflow_dispatch` case added, we should be able to run the workflow for certain branches :) At least that seems to be the case with the current full CI workflow: 

image

**Comment by JKRhb** [comment]
Hmm. On second thought, that probably does not change the CI matrix. Maybe there could be another case added for that?

**Comment by JKRhb** [comment]
> Hmm. On second thought, that probably does not change the logic within the CI matrix. Maybe there could be another case added for that?

Not entirely sure if it works, but if it does, the last commit should have added it in ;)

**Comment by relu91** [comment]
I'm not entirely convinced about narrowing down the matrix to only work on merge. I would like to know immediately if a PR is breaking and fix the errors in the PR. I appreciate the effort, but my preference would be to wait longer and be sure that we have all greens.

**Comment by JKRhb** [comment]
> I'm not entirely convinced about narrowing down the matrix to only work on merge. I would like to know immediately if a PR is breaking and fix the errors in the PR. I appreciate the effort, but my preference would be to wait longer and be sure that we have all greens.

Yeah, I think we can definitely go this route, as mentioned in the issue, the total time is now about 8 minutes which should be fine as, if something should be completely broken, we will notice it much earlier on `ubuntu-latest`. I will open another PR as an alternative to this one.

**Comment by JKRhb** [comment]
I just opened #1121 as alternative :)

**Pull request closed without merging**
