### PR TITLE
chore(CI): add Node.js 22 to matrix

### PR DESCRIPTION
**Pull request by danielpeintner**
fixes https://github.com/eclipse-thingweb/node-wot/issues/1273

### CODE REVIEW

**Comment by danielpeintner** [comment]
> npm ERR! code 1
> npm ERR! path /home/runner/work/node-wot/node-wot/node_modules/node-mbus

mbus seems to cause issues on Node.js 22

**Comment by danielpeintner** [comment]
BTW, I created https://github.com/Apollon77/node-mbus/issues/123

**Comment by danielpeintner** [comment]
I messed up mbus with modbus 🙈

**Comment by danielpeintner** [comment]
The new error seems to stem from a wrong node installation!?!

https://github.com/eclipse-thingweb/node-wot/actions/runs/8878604576/job/24374716602?pr=1274

**Comment by danielpeintner** [comment]
Seems to be related with https://github.com/nodejs/node/issues/52682

**Comment by relu91** [comment]
Should we go with [this suggestion](https://github.com/nodejs/node/issues/52682#issuecomment-2090974281) ?

**Comment by danielpeintner** [comment]
> Should we go with [this suggestion](https://github.com/nodejs/node/issues/52682#issuecomment-2090974281) ?

No longer needed since the GH workflow should pick the latest Node.js 22.x version.
Re-running the workflow seems to show that

https://github.com/eclipse-thingweb/node-wot/actions/runs/8878604576/job/24558179052?pr=1274#step:3:91

Anyhow, we are now running into other issues 😒

Now, I think they are really mbus-related.
https://github.com/eclipse-thingweb/node-wot/actions/runs/8878604576/job/24558179052?pr=1274#step:5:25

I will take a closer look next week...

**Comment by danielpeintner** [comment]
Created https://github.com/Apollon77/node-mbus/issues/124

**Comment by danielpeintner** [comment]
mbus issue should be resolved (see https://github.com/Apollon77/node-mbus/issues/124#issuecomment-2102852295). We just need to wait till 2.24 is published.

**Comment by danielpeintner** [comment]
I am seeing logs like this for Node.js 22

`(node:4256) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.`

This might be solved by updating AJV. see https://stackoverflow.com/a/77929792
I will try.

OR

```
2024-06-05T15:17:05.296Z node-wot:cli:cli-default-servient:error Servient found error in privileged script 'script' Bad synchronous error in Servient sandbox
(node:6876) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
```

Here I am not sure. Is it a "vm2" issue?
@relu91

**Pull request closed without merging**
