### PR TITLE
refactor: remove unnecessary `new Promise` wrappers

### LINKED ISSUE #569: Promise async code style
_input from @erossignon_ 

We have different code styles used throughout the code for promises.

```JS
method(...): Promise<...> {
  return new Promise<...>((resolve, reject) => {
    // actual code
  }
}
```

or

```JS
async method(...): Promise<...> {
    // actual code
}
```

Shall we leave it as is or go with one or the other?
The 2nd variant seems cleaner and less verbose. I don't believe there is any downside...

### PR DESCRIPTION
**Pull request by JKRhb**
This PR contributes to resolving #569. There are a few instances of the `return Promise` pattern left that were a bit difficult to resolve, though, so I am not sure whether we should keep the issue open?

### CODE REVIEW

**Review by danielpeintner — APPROVED** [review]
I looked trough the changes and they seem all fine by me 👍

I would also argue after merging this PR we should close https://github.com/eclipse-thingweb/node-wot/issues/569.

**Review by relu91 — APPROVED** [review]
Looks good! regarding the issue linked, I think it might be difficult to be sure that every non-necessary promise it has been removed. I remember finding an [eslint extension](https://eslint-plugin-es.mysticatea.dev/rules/no-promise.html)... maybe we could resolve it once the extension is in place and the non-convertible cases are correctly opted out.

**Comment by relu91** [comment]
Given we have two approvals I'm merging, let's wait for the eslint rule before closing #569

**Comment by JKRhb** [comment]
That sounds good :) I updated the PR description before your merge so that #569 will stay open.

> Looks good! regarding the issue linked, I think it might be difficult to be sure that every non-necessary promise it has been removed. I remember finding an [eslint extension](https://eslint-plugin-es.mysticatea.dev/rules/no-promise.html)... maybe we could resolve it once the extension is in place and the non-convertible cases are correctly opted out.

**Pull request merged**
