### PR TITLE
chore: increase version numbers to 0.8.14 for next release

### PR DESCRIPTION
**Pull request by danielpeintner**
FYI: As usual, every time we update the node-wot package versions we also newly create `package-lock.json` to update dependencies.
Hence one can see many changes for `package-lock.json` ...

### CODE REVIEW

**Review by egekorkan — APPROVED** [review]

**Comment by danielpeintner** [comment]
> I don't see what is failing?

I don't see / understand it either ... it just says

`Error: Process completed with exit code 1.`

https://github.com/eclipse-thingweb/node-wot/actions/runs/8643957815/job/23708890898?pr=1264#step:9:518

**Comment by danielpeintner** [comment]
> Me neither, 🤔 upgrading the numbers without re-generate package-lock is not possible, right? Tomorrow I'll try locally if somehow I can reproduce the error.

Locally it runs fine. Moreover, also the CI for some platforms runs fine.. seems to be a CI issue?

**Comment by danielpeintner** [comment]
It seems to be a vm2 issue.
Anyhow, the vm2 version did not change in `package-lock.json`, it is still `3.9.18` 😒

**Comment by relu91** [comment]
I tried locally and I'm not sure is vm2 fault. I get the same errors but the tests complete. I'm afraid that the error logged are supposed to be there as we are actually testing for them to happen. See my local output:
```bash
  Test suite for script runtime
  node-wot:cli:cli-default-servient:debug DefaultServient configured with +0ms
  node-wot:cli:cli-default-servient:debug [object Object] +0ms
  node-wot:core:servient:debug Servient adding client factory for 'file' +0ms
  node-wot:core:servient:debug Servient adding client factory for 'http' +0ms
  node-wot:core:servient:debug Servient adding client factory for 'https' +0ms
  node-wot:core:servient:debug Servient adding client factory for 'coap' +1ms
  node-wot:core:servient:debug Servient adding client factory for 'coaps' +0ms
  node-wot:core:servient:debug Servient adding client factory for 'mqtt' +0ms
  node-wot:cli:cli-default-servient:info DefaultServient started +0ms
  node-wot:core:wot-impl:debug WoTImpl producing new ExposedThing 'servient' +0ms
  node-wot:core:servient:warn Servient generating ID for 'servient': 'urn:uuid:d2d21ae6-daf1-455b-a0d0-04b3b41d2535' +0ms
  node-wot:core:servient:debug Servient reset ID 'urn:uuid:d2d21ae6-daf1-455b-a0d0-04b3b41d2535' with 'servient' +3ms
  node-wot:core:exposed-thing:debug ExposedThing 'servient' setting action handler for 'setLogLevel' +0ms
  node-wot:core:exposed-thing:debug ExposedThing 'servient' setting action handler for 'shutdown' +0ms
  node-wot:core:exposed-thing:debug ExposedThing 'servient' setting action handler for 'runScript' +0ms
  node-wot:core:exposed-thing:debug ExposedThing 'servient' setting read handler for 'things' +0ms
  node-wot:core:exposed-thing:debug ExposedThing 'servient' exposing all Interactions and TD +0ms
  node-wot:core:servient:warn Servient has no servers to expose Things +1ms
    ✔ should provide cli args
    ✔ should use the compiler function
    ✔ should provide env variables
    ✔ should hide system env variables
    ✔ should require node builtin module
  node-wot:cli:cli-default-servient:error Servient caught Servient found error in script 'script' and halted with Error: Synchronous error in Servient sandbox
  node-wot:cli:cli-default-servient:error     at script:1:69
  node-wot:cli:cli-default-servient:error     at VM2 Wrapper.apply (E:\Progetti\reluWoT\node_modules\vm2\lib\bridge.js:485:11)
  node-wot:cli:cli-default-servient:error     at NodeVM.run (E:\Progetti\reluWoT\node_modules\vm2\lib\nodevm.js:497:23)
  node-wot:cli:cli-default-servient:error     at DefaultServient.runScript (E:\Progetti\reluWoT\packages\cli\src\cli-default-servient.ts:191:23)
  node-wot:cli:cli-default-servient:error     at E:\Progetti\reluWoT\packages\cli\test\RuntimeTest.ts:107:37
  node-wot:cli:cli-default-servient:error     at Proxy.assertThrows (E:\Progetti\reluWoT\node_modules\chai\lib\chai\core\assertions.js:2644:7)
  node-wot:cli:cli-default-servient:error     at Proxy.methodWrapper (E:\Progetti\reluWoT\node_modules\chai\lib\chai\utils\addMethod.js:57:25)
  node-wot:cli:cli-default-servient:error     at Function.assert.doesNotThrow (E:\Progetti\reluWoT\node_modules\chai\lib\chai\interface\assert.js:2028:20)
  node-wot:cli:cli-default-servient:error     at WoTRuntimeTest.should catch synchronous errors (E:\Progetti\reluWoT\packages\cli\test\RuntimeTest.ts:106:16)
  node-wot:cli:cli-default-servient:error     at Context.should catch synchronous errors (E:\Progetti\reluWoT\node_modules\@testdeck\core\index.ts:180:27) +0ms
  node-wot:cli:cli-default-servient:error Servient caught Servient found error in privileged script 'script' and halted with Error: Synchronous error in Servient sandbox
  node-wot:cli:cli-default-servient:error     at script:1:69
  node-wot:cli:cli-default-servient:error     at VM2 Wrapper.apply (E:\Progetti\reluWoT\node_modules\vm2\lib\bridge.js:485:11)
  node-wot:cli:cli-default-servient:error     at NodeVM.run (E:\Progetti\reluWoT\node_modules\vm2\lib\nodevm.js:497:23)
  node-wot:cli:cli-default-servient:error     at DefaultServient.runPrivilegedScript (E:\Progetti\reluWoT\packages\cli\src\cli-default-servient.ts:240:23)
  node-wot:cli:cli-default-servient:error     at E:\Progetti\reluWoT\packages\cli\test\RuntimeTest.ts:110:37
  node-wot:cli:cli-default-servient:error     at Proxy.assertThrows (E:\Progetti\reluWoT\node_modules\chai\lib\chai\core\assertions.js:2644:7)
  node-wot:cli:cli-default-servient:error     at Proxy.methodWrapper (E:\Progetti\reluWoT\node_modules\chai\lib\chai\utils\addMethod.js:57:25)
  node-wot:cli:cli-default-servient:error     at Function.assert.doesNotThrow (E:\Progetti\reluWoT\node_modules\chai\lib\chai\interface\assert.js:2028:20)
  node-wot:cli:cli-default-servient:error     at WoTRuntimeTest.should catch synchronous errors (E:\Progetti\reluWoT\packages\cli\test\RuntimeTest.ts:109:16)
  node-wot:cli:cli-default-servient:error     at Context.should catch synchronous errors (E:\Progetti\reluWoT\node_modules\@testdeck\core\index.ts:180:27) +2ms
    ✔ should catch synchronous errors
  node-wot:cli:cli-default-servient:error Servient found error in script 'script' Bad synchronous error in Servient sandbox +4ms
  node-wot:cli:cli-default-servient:error Servient found error in privileged script 'script' Bad synchronous error in Servient sandbox +2ms
    ✔ should catch bad errors
  node-wot:cli:cli-default-servient:error Servient caught Asynchronous script error 'script' that threw string instead of Error
  node-wot:cli:cli-default-servient:error     Bad asynchronous error in Servient sandbox +3ms
    ✔ should catch bad asynchronous errors for runScript
  node-wot:cli:cli-default-servient:error Servient caught Asynchronous script error 'script' that threw string instead of Error
  node-wot:cli:cli-default-servient:error     Bad asynchronous error in Servient sandbox +3ms
    ✔ should catch bad asynchronous errors  for runPrivilegedScript
  node-wot:binding-mqtt:mqtt-client-factory:debug MqttClientFactory stopping all clients for 'mqtt' +0ms
```

**Comment by relu91** [comment]
Not sure if it is an issue but on windows it seems unable to cleanly do `npm ci` https://github.com/eclipse-thingweb/node-wot/actions/runs/8643957815/job/23741626112?pr=1264#step:5:13.

**Comment by relu91** [comment]
added a minor change because lately, I've configured a bunch of repositories with husky and the [doc suggests ](https://typicode.github.io/husky/how-to.html#ci-server-and-docker)disabling it in the CI. I'm not expecting it to resolve the error but still let's try :).

**Comment by danielpeintner** [comment]
> Not sure if it is an issue but on windows it seems unable to cleanly do `npm ci` https://github.com/eclipse-thingweb/node-wot/actions/runs/8643957815/job/23741626112?pr=1264#step:5:13.

On my windows machine (node: v18.14.2 and npm: 9.5.0) I don't have this problem. @relu91 do you have it locally also?

**Comment by danielpeintner** [comment]
With  https://github.com/eclipse-thingweb/node-wot/pull/1264/commits/a0c5a7a528178ced97fa0a240d91791af7384db7 I updated the `package-lock.json` only with the *new* node-wot version changes only.

This seems to work. Anyhow, I think we seem to have a problem somewhere and we want (and need) to update dependencies in the future also.
Anyhow, for now I would go with this solution.

**Review by JKRhb — APPROVED** [review]

**Pull request merged**
