### PR TITLE
feat(core): add helper function to fetch a TD

### PR DESCRIPTION
**Pull request by danielpeintner**
fixes https://github.com/eclipse-thingweb/node-wot/issues/1055

### CODE REVIEW

**Comment by relu91** [comment]
Shouldn't we deprecate this helper function and favor the new #1166?

**Comment by danielpeintner** [comment]
> Shouldn't we deprecate this helper function and favor the new #1166?

W.r.t. `fetchTD()` ... there should be just one piece of code dealing with it, true, point taken 👍.

I am wondering what we should do w.r.t. to the existing `fetch()`. Remove it? Helpers usually offers static functions, the only exception is `fetch()` which needs a `Servient` to work. I would think we should remove the function "on the long run"...

Moreover, there is the interface `Resolver` which is used by ThingModel code.. this is somewhat not very clear to me.

**Comment by relu91** [comment]
Yes, I would deprecate the `fetch` and `fetchTD` functions in favor of `requestThingDescription`. 

> Moreover, there is the interface Resolver which is used by ThingModel code.. this is somewhat not very clear to me.

The interface is there to not depend on the Core from the ThingModelHelpers pov. Users can decide to use the ThingModel helpers without using the Core package and implement their own resolver. I think we can appreciate this choice when we move the tool to a new repo.

**Comment by danielpeintner** [comment]
> Yes, I would deprecate the `fetch` and `fetchTD` functions in favor of `requestThingDescription`.

deprecate `fetch` is possible but at the moment it is still used.
Let's wait till https://github.com/eclipse-thingweb/node-wot/pull/1166 has been integrated and take a look to replace all usages.
Anyhow, ThingModel still uses `fetch`.. I believe.. but let's see...

deprecate `fetchTD` is not necessary since it hasn't been pushed yet.

**Comment by danielpeintner** [comment]
Closing in favor of https://github.com/eclipse-thingweb/node-wot/pull/1183

**Pull request closed without merging**
