### PR TITLE
refactor: revert back to *old* way of cloning

### PR DESCRIPTION
**Pull request by danielpeintner**
Note: reverts parts of https://github.com/eclipse-thingweb/node-wot/pull/1105

fixes https://github.com/eclipse-thingweb/node-wot/issues/1151

### CODE REVIEW

**Comment by danielpeintner** [comment]
The issue with starting `node packages\cli\dist\cli.js examples\scripts\counter.js` is gone but the exposed thing immediately shuts down and the "server" part is not active anymore...

**Comment by danielpeintner** [comment]
We run into the case where no server is there...

https://github.com/eclipse-thingweb/node-wot/blob/8659709b76c346ce0c2d5ce768f113bb56e4777c/packages/core/src/servient.ts#L39-L44

2 questions:
* why does this happen?
* why is the warn statement not printed out ?

**Comment by danielpeintner** [comment]
I found the problem, see https://github.com/eclipse-thingweb/node-wot/pull/1152/commits/2976374a3cfe3f2f1143776dc10260b4ad24025e

Question: I wonder whether the clientOnly flag is properly initialed...

https://github.com/eclipse-thingweb/node-wot/pull/1152/files#diff-d50fb68661fd819c0149ceef494c0015de6739c57acd49363e2ba04d6aa0eda3L99-L102

I would rather write something like..

```
        // apply flags
        this.config.servient ??= {};
        this.config.servient.clientOnly = clientOnly;
```

Any thoughts?

**Comment by JKRhb** [comment]
Thank you, @danielpeintner, for providing this fix! After also doing some more research, I discovered that the problem might be related to `vm2`, since the error does not occur if you perform a `structuredClone` of an `ExposedThingInit` before passing it to the `produce` method (which I found pretty odd). Apparently, `vm2` wraps unprocessed JavaScript objects somehow, so that they are not compatible with `structuredClone` anymore. With the old parse-stringify approach, this problem does not seem to be present. 

I guess we could revisit using the more recommended `structuredClone` once again when a replacement for `vm2` has been added to the code. For now, maybe we need to make sure that the problem does not appear in other CLI-related contexts as well.

I am really sorry that this problem arose, I didn't anticipate this kind of behavior from the CLI :/ Really great that you discovered the solution so quickly, though!

**Comment by JKRhb** [comment]
> Question: I wonder whether the clientOnly flag is properly initialed...
> 
> https://github.com/eclipse-thingweb/node-wot/pull/1152/files#diff-d50fb68661fd819c0149ceef494c0015de6739c57acd49363e2ba04d6aa0eda3L99-L102
> 
> I would rather write something like..
> 
> ```
>         // apply flags
>         this.config.servient ??= {};
>         this.config.servient.clientOnly = clientOnly;
> ```
> 
> Any thoughts?

That is definitely a much simpler solution and looks good to me! I think the current state resulted to a certain extent from the version we had before where the `servient` field was not always defined (or only when `clientOnly` was "truthy"). Maybe we need to double-check that this slight logic change would still work but other than that I am very much in favor of this change.

**Comment by danielpeintner** [comment]
> That is definitely a much simpler solution and looks good to me!

@relu91 are you fine with the suggested change as part of this PR also?

**Review by relu91 — APPROVED** [review]
Yes good to go, and thanks for digging this down. VM2 is getting problematic :/

**Pull request merged**
