### PR TITLE
Update Asset Interfaces Description (AID) submodel

### PR DESCRIPTION
**Pull request by danielpeintner**
fixes https://github.com/eclipse-thingweb/node-wot/issues/1220

### CODE REVIEW

**Comment by danielpeintner** [comment]
@Kaz040 please have a look

Note: I think all aspects are handled, some terms like `created`, `modified` etc were not there before. Maybe we can add them later in a follow-up PR.

I also had to update the JSON Schema, see https://github.com/eclipse-thingweb/node-wot/pull/1222/files#diff-e8f82d52b6ce8affc67a761291254515c7bf70157338602673288f93a32fb45b
The only thing is missing are the 2 _new_ terms `mostSignificantByte` and `mostSignificantWord` for Modbus. Do you want to update the JSON I already modified with those 2 missing changes?

**Review by Kaz040 — APPROVED** [review]
From my side. everything seems ok according to the changes.

**Comment by danielpeintner** [comment]
@sebastiankb fine with merging too?

**Review by sebastiankb — APPROVED** [review]

**Comment by sebastiankb** [comment]
PR looks good. Ready for merge

**Pull request merged**
